INSERT INTO t_p63666683_game_squad_compariso.treaties
  (id, name, description, compatible_classes, compatible_subtypes, rarity, avatar_url, category_id, stat_modifiers, stat_modifiers_ex, compatible_unit_ids, is_active)
VALUES
('cbgg-sword-cavalry-doctrine-v', 'Доктрина мечной кавалерии V', 'Открывает навык «Яростный удар». Юнит немедленно наносит удар сверху, а затем продвигается вперёд, нанося до трёх дополнительных атак. Может поражать до 2 дополнительных целей за раз.', ARRAY['Кавалерия','Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/1b2f33e654d64d9e8cfb926cdd46a482.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-sword-militia-s-doctrine-ii', 'Доктрина ополчения с мечами II', 'Уменьшает получаемый урон от стрелков на 160.', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/9d37ce6654ac469990181760b990b204.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-tactic-falcon', 'Тактика: Сокол', 'Не распространяется на некоторых особых юнитов Эффект: увеличивает урон по стрелкам на 15%', ARRAY[]::text[], ARRAY[]::text[], 'epic', '', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-tactic-trench-warfare', 'Тактика: Окопная война', 'Когда огнестрельные юниты не выполняют команду движения, они получают эффект «Оборонительные сооружения» через 10 секунд. Эффект не стакается; команды без движения сбрасывают таймер, но не снимают эффект. Любая команда движения снимает эффект «Оборонительные сооружения». «Оборонительные сооружения»: при получении дальнего урона от вражеских юнитов 70% урона преобразуется в эффект отбрасывания, после чего эффект исчезает. Если юниты не выполняют команду движения, эффект «Оборонительные сооружения» восстанавливается через 10 секунд.', ARRAY['Стрелки']::text[], ARRAY['Стрелковая пехота - аркебузиры']::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/35d1bfd0fa744dbd9313cbc676c6c681.webp', 20, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-tenant-farmers-doctrine-ii', 'Доктрина арендных фермеров II', 'Уменьшает получаемый урон в ближнем бою на 160.', ARRAY['Пехота']::text[], ARRAY['Пехота ближнего боя - пики']::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/db76cea131364aafb8f6c5a13a3f4d7f.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-tiger-fists-dread-roar', 'Кулаки тигра: Рёв ужаса', 'Навык «Ярость тигра» снижает урон вражеского юнита на 15% на 5 секунд.', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/72ffe0fba90746c59cd26f6b816d3559.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-tiger-fists-swift-stance', 'Кулаки тигра: Быстрая стойка', 'Уменьшает перезарядку навыка «Могучий шлепок» на 5 сек.', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/72ffe0fba90746c59cd26f6b816d3559.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-toughness-doctrine-v', 'Доктрина стойкости V', 'Получаемый урон снижается на 33%. Этот эффект ослабевает при каждом получении урона и полностью исчезает после 8 попаданий.', ARRAY['Кавалерия','Пехота','Стрелки']::text[], ARRAY['Пехота ближнего боя - пики','Стрелковая пехота - арбалетчики']::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/e2221501b9d24d73b33ac49b41e2fa17.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-unit-damage-doctrine-v', 'Доктрина урона юнита V', 'Увеличивает наносимый по юниту урон на 120 очков, Увеличивает все виды урона на 80 очков.', ARRAY[]::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/45b233171ab748ab89b7a3870d80f68a.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-unshakable-ward', 'Непоколебимая защита', 'Изучает навык «Эгида Ачалы» Эффект: при активации снижает получаемый длительный урон на 75% и даёт иммунитет к оглушению и отбрасыванию. Длительность: 7 сек. +1 ещё...', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', '', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-vanguard-doctrine-v', 'Доктрина авангарда V', 'Побуждает особую пехоту смело идти в атаку. После каждой атаки скорость передвижения увеличивается на 30% на 5 секунд.', ARRAY[]::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/3c7b0df0c0dd4e9c817c238fc1aa15fd.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-varangian-axe-doctrine', 'Доктрина топора варягов', 'Увеличивает урон навыка «Разбивающий щит» на 10%.', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/9680562ae059417ea413b5e9196f5507.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-varangian-sword-doctrine-ii', 'Доктрина меча варягов II', 'Уменьшает получаемый урон варяжской стражи в ближнем бою на 5%.', ARRAY['Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/9680562ae059417ea413b5e9196f5507.webp', 18, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-victory-rush-doctrine-v', 'Доктрина победного рывка V', 'Позволяет сабельной кавалерии легко продолжать натиск. Атаки в ближнем бою заставляют пехоту и копейную кавалерию наносить на 80% меньше урона и не двигаться в течение 2 секунд.', ARRAY['Кавалерия','Пехота']::text[], ARRAY[]::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/da7bd7feb14e4e0ba5fcb409526993aa.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-whistling-arrow-doctrine-v', 'Доктрина свистящей стрелы V', 'Каждое 3-е попадание накладывает кровотечение на врагов в размере 12% от их текущего здоровья; может срабатывать совместно с другими юнитами.', ARRAY['Стрелки']::text[], ARRAY['Стрелковая пехота - лучники']::text[], 'epic', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/e94c55a40a3a4b3583b77e8b723cbe2b.webp', 20, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true)
ON CONFLICT (id) DO NOTHING;
