INSERT INTO t_p63666683_game_squad_compariso.treaties
  (id, name, description, compatible_classes, compatible_subtypes, rarity, avatar_url, category_id, stat_modifiers, stat_modifiers_ex, compatible_unit_ids, is_active)
VALUES
('cbgg-common-piercing-defence-doctrine', 'Обычная доктрина проникающей защиты', 'Увеличивает проникающую защиту на 50.', ARRAY[]::text[], ARRAY[]::text[], 'common', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/aaed4e0053ef423988439ca1e0773860.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-common-piercing-doctrine', 'Обычная доктрина проникающей бронебойности', 'Увеличивает проникающую бронебойность на 60.', ARRAY['Кавалерия','Пехота','Стрелки']::text[], ARRAY['Пехота ближнего боя - большой щит','Пехота ближнего боя - дротики','Пехота ближнего боя - пики']::text[], 'common', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/121c4c6bb6534d9c875e049c2569289e.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-common-slashing-damage-doctrine', 'Обычная доктрина рубящего урона', 'Увеличивает рубящий урон на 50.', ARRAY['Кавалерия','Пехота','Стрелки']::text[], ARRAY['Пехота ближнего боя - баклер','Пехота ближнего боя - пики','Стрелковая пехота - аркебузиры']::text[], 'common', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/75a5c6e71a214816bf00962c913616d1.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-common-slashing-defence-doctrine', 'Обычная доктрина рубящей защиты', 'Увеличивает рубящую защиту на 50.', ARRAY[]::text[], ARRAY[]::text[], 'common', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/296459e5913f44b588733509afcf5b6a.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true),
('cbgg-common-slashing-doctrine', 'Обычная доктрина рубящей бронебойности', 'Увеличивает рубящую бронебойность на 60.', ARRAY['Кавалерия','Пехота','Стрелки']::text[], ARRAY['Пехота ближнего боя - баклер','Пехота ближнего боя - пики','Стрелковая пехота - аркебузиры']::text[], 'common', 'https://cdn.poehali.dev/projects/455c24fb-ce5d-4076-9543-1ca6ad6daa72/bucket/treaties/08655733cadb49f09c0fffe454bda8fd.webp', 21, '{}'::jsonb, '{}'::jsonb, ARRAY[]::text[], true)
ON CONFLICT (id) DO NOTHING;
